#makefile variabile usa per piu esercitazioni è quello generale; da copiare direttamente
CC=gcc
#parametro utilizzato dal compilatore C
CFLAG=-Wall
SRC = $(wildcard *.c)
TAR = $(SRC:.c=)

all: $(TAR)

%: %.CC
		$(CC) $(FLAG)	$< -o $@
		
